### ISSUE TITLE
Enable template repo

### ISSUE THREAD

**Issue by ha0ye** [weecology/livedat-github-actions#3]
GitHub now has a feature where repos can be designated as "template repos". This can save users some steps compared to the old workflow of import and clone, by adding a button:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository

Could also be applied to https://github.com/weecology/livedat, I think?

**Comment by rudeboybert** [comment]
Great idea! I just activated it and now there is a "Use this template" button. I'll add a TODO to the tutorial webpage source code repo to "add note about import/clone old way vs use template new way". thanks
