### ISSUE TITLE
Package ‘livedatagithubactions’ is not available for the latest version of R

### ISSUE THREAD

**Issue by Songleemei** [weecology/livedat-github-actions#4]
Hi, I am trying to follow the quickstart tutorial for the GitHub Actions. When it comes to step 7 (Add Data Code), the Actions always report failed with the R-CMD-check sending a warning when checking whether package "livedatagithubactions" can be installed. Then I found out that this "livedatagithubactions" package is currently not available for R version 4.2.3 (2023-03-15) -- "Shortstop Beagle". Is this the cause of the failed action? And is there any other solutions instead of just degrading R to apply this package? Thank you so much!

![image](https://user-images.githubusercontent.com/92319822/229020571-f722f604-035c-44d3-8841-47769402da1f.png)

**Comment by rudeboybert** [comment]
Hi @Songleemei thanks for posting this. I got the tutorial to work on my end, but I noticed that your [R-CMD-check.yaml](https://github.com/Songleemei/livedat-github-actions/blob/main/.github/workflows/R-CMD-check.yaml) is different than [mine](https://github.com/rudeboybert/live-data/blob/master/.github/workflows/data-tests.yaml). Could you try replacing yours with mine and letting me know if GA jobs completes? If so, I need to update the tutorial.

**Comment by Songleemei** [comment]
Hi @rudeboybert, thanks for replying! Yes, your .yaml file works, but there are several annotations:
<img width="1143" alt="Screenshot 2023-04-05 at 1 29 14 PM" src="https://user-images.githubusercontent.com/92319822/229989118-a229146f-cb59-4ae8-aadd-19bcdae40f11.png">

Therefore, I updated actions/checkout@v2 to actions/checkout@v3, r-lib/actions/setup-r@v1 to r-lib/actions/setup-r@v2. And it still works, with only one annotation left: 
<img width="1162" alt="Screenshot 2023-04-05 at 1 32 45 PM" src="https://user-images.githubusercontent.com/92319822/229989649-2e8bcd79-c32f-4993-bdf5-c2f20bbb7b4a.png">

For my [R-CMD-check.yaml](https://github.com/Songleemei/livedat-github-actions/blob/main/.github/workflows/R-CMD-check.yaml), it is from the template repository. And I found out that the check-r-package@v2 actually was the main reason of causing the warning and test failure, my .yaml file can work after I delete the code "- uses: r-lib/actions/check-r-package@v2". Therefore, although I don't know the difference, feels like either your .yaml file or the .yaml file from the template repository without the code "- uses: r-lib/actions/check-r-package@v2" can work!

**Comment by rudeboybert** [comment]
ok great! I'll update the tutorial with the info here later on. thanks for bringing this to our attention

**Comment by Songleemei** [comment]
No worries, also thanks for sending me the .yaml file. Then I just close with comment. All the best!

**Comment by fjoyce** [comment]
Hi! Thanks for creating the quickstart tutorial and template repo.

I had similar issues as @Songleemei (https://github.com/weecology/livedat-github-actions/issues/5).

I think one of the root causes is that the tutorial instructions say to use usethis::use_github_actions(), but that function is now deprecated (https://usethis.r-lib.org/reference/use_github_actions.html), so that results in the differences in the R-CMD-check.yaml file.

Maybe using usethis:use_github_action() instead would prevent the inclusion of r-lib/actions/check-r-package@v2? I haven't tried that yet.
